# Generated by Django 5.2.17 on 2026-09-20 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('JOB_SEEKER', 'Job Seeker'), ('RECRUITER', 'Recruiter')], max_length=100)),
                ('headline', models.CharField(blank=True, max_length=20)),
                ('skills', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_public', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
